query AllGames {
  games (pagination: {limit: -1}){
    data {
      id
      attributes{
        date
        title
        players (pagination: {limit: -1}){
          data {
            id
          }
        }
      }
    }
  }
}